// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzioE7GxHH45GjzHr-XlCUe7ycC40JCvc',
    appId: '1:902477245270:web:ce7be0462c50b8cc2044f7',
    messagingSenderId: '902477245270',
    projectId: 'libmate-we158-ceb13',
    authDomain: 'libmate-we158-ceb13.firebaseapp.com',
    storageBucket: 'libmate-we158-ceb13.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29ippE3cSpvuQxrAcjjJA19lRzKanH_E',
    appId: '1:902477245270:ios:31efe2277c5617cd2044f7',
    messagingSenderId: '902477245270',
    projectId: 'libmate-we158-ceb13',
    storageBucket: 'libmate-we158-ceb13.firebasestorage.app',
    iosBundleId: 'com.example.libmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD29ippE3cSpvuQxrAcjjJA19lRzKanH_E',
    appId: '1:902477245270:ios:31efe2277c5617cd2044f7',
    messagingSenderId: '902477245270',
    projectId: 'libmate-we158-ceb13',
    storageBucket: 'libmate-we158-ceb13.firebasestorage.app',
    iosBundleId: 'com.example.libmateApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP876Qt-DeA7mU39n20VK2r5ISSS5_x8Q',
    appId: '1:902477245270:android:b622f261189ac71a2044f7',
    messagingSenderId: '902477245270',
    projectId: 'libmate-we158-ceb13',
    storageBucket: 'libmate-we158-ceb13.firebasestorage.app',
  );
}
